version: '3'

services:
  app:
    image: fadhlanhazmi/dummy-app:1.0.0
    network_mode: host

  filebeat:
    image: fadhlanhazmi/filebeat:1.0.0
    network_mode: host
    volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"