version: '3'

services:
  app:
    image: fadhlanhazmi/dummy-app:1.0.0
    network_mode: host

  filebeat:
    image: fadhlanhazmi/filebeat:1.0.0
    restart: always
    network_mode: host
    volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      HOSTS="10.128.0.101,10.128.0.102,10.128.0.103"
      LOG_PATH="/usr/share/dockerlogs/data"
      INDEX="interns-%{[beat.version]}-%{+yyyy.MM.dd}"
      EXCLUDE_LINES=".*INFO.*,.*WARN.*"
      JSON_FIELDS="log,message"
      LOGGING_LEVEL="warning"
      STREAM="all"