filebeat.inputs:
- type: docker
  combine_partial: true
  containers:
    path: "/usr/share/dockerlogs/data"
    stream: "all"
    ids:
      - "*"
  exclude_lines: ".*INFO.*,.*WARN.*"
  ignore_older: 10m

processors:
  # decode the log field (sub JSON document) if JSON encoded, then maps it's fields to elasticsearch fields
- decode_json_fields:
    fields: "log,message"
    target: ""
    # overwrite existing target elasticsearch fields while decoding json fields    
    overwrite_keys: true
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# setup filebeat to send output to elasticsearch
output.elasticsearch:
  hosts: ["http://10.128.0.101:9200","http://10.128.0.102:9200","http://10.128.0.103:9200"]
  index: "interns-%{[beat.version]}-%{+yyyy.MM.dd}"

setup.template.name: "interns"
setup.template.pattern: "interns-*"

logging.level: "warning"
logging.json: true