version: '3'

services:
  app:
    image: fadhlanhazmi/dummy-app:1.0.0
    network_mode: host
    build:
      context: dummy-app
      dockerfile: Dockerfile

  filebeat:
    image: fadhlanhazmi/filebeat:1.0.0
    restart: always
    network_mode: host
    build:
      context: filebeat
      dockerfile: Dockerfile
      args:
        - version=7.1
    volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      HOSTS: "localhost:9200,localhost:9201,localhost:9202"
      LOG_PATH: "/usr/share/dockerlogs/data"
      INDEX: "interns-%{[beat.version]}-%{+yyyy.MM.dd}"
      EXCLUDE_LINES: ".*INFO.*,.*WARN.*"
      JSON_FIELDS: "log,message"
      LOGGING_LEVEL: "warning"
      STREAM: "all"

  kibana:
    image: fadhlanhazmi/kibana:1.0.0
    build:
      context: kibana
      dockerfile: Dockerfile
    environment:
      - LOGGING_QUIET=true
      - hosts=["http://localhost:9200","http://localhost:9201","http://localhost:9202"]
    network_mode: host

  elasticsearch1:
    hostname: elasticsearch1
    image: fadhlanhazmi/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - master=true
      - data=true
      - port=9200
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch2:
    hostname: elasticsearch2
    image: fadhlanhazmi/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - master=true
      - data=true
      - port=9201
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch3:
    hostname: elasticsearch3
    image: fadhlanhazmi/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - master=true
      - data=true
      - port=9202
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1