version: '3'

services:
  app:
    image: fadhlanhazmi/dummy-app:1.0.0
    network_mode: host
    build:
      context: dummy-app
      dockerfile: Dockerfile

  filebeat:
    image: fadhlanhazmi/filebeat:1.0.0
    restart: always
    network_mode: host
    build:
      context: filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "./local-config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"

  kibana:
    image: fadhlanhazmi/kibana:1.0.0
    build:
      context: kibana
      dockerfile: Dockerfile
    environment:
      - LOGGING_QUIET=true
    volumes:
      - - "./local-config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    network_mode: host

  elasticsearch1:
    hostname: elasticsearch1
    image: fadhlanhazmi/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - node.name=es-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - port=9200
    volumes:
      - "./local-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch2:
    hostname: elasticsearch2
    image: fadhlanhazmi/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - node.name=es-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - port=9201
    volumes:
      - "./local-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch3:
    hostname: elasticsearch3
    image: fadhlanhazmi/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - node.name=es-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - port=9202
    volumes:
      - "./local-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1