version: '3'

services:
  kibana:
    image: fadhlanhazmi/kibana:1.0.0
    environment:
      - LOGGING_QUIET=true
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    network_mode: host