version: '3'

services:
  elastalert:
    image: elastalert:latest
    
    network_mode: host
    volumes:
      - "./config.yaml:/opt/elastalert/config.yaml:ro"
      - "./rules.yaml:/opt/elastalert/rules/rules.yaml:ro"