filebeat.inputs:
- type: log
  paths:
    - /usr/share/log/uwsgi.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# setup filebeat to send output to elasticsearch
output.elasticsearch:
  hosts: ["http://localhost:9200"]
  index: "arisan-viewmidware-%{+yyyy.MM.dd}"

setup.template.name: "arisan-viewmidware"
setup.template.pattern: "arisan-viewmidware*"

logging.level: "warning"
logging.json: true