filebeat.inputs:
- type: log
  paths:
    - /usr/share/log/uwsgi.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# setup filebeat to send output to elasticsearch
output.elasticsearch:
  hosts: ["http://localhost:9200","http://localhost:9201","http://localhost:9202"]
  index: "arisan-web"

setup.template.name: "arisan-web"
setup.template.pattern: "arisan-web-*"

logging.level: "warning"
logging.json: true