version: '3'

services:
  elasticsearch:
    hostname: elasticsearch
    image: fadhlanhazmi/elasticsearch:1.0.0
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - port=9200
      - HOSTNAME=${HOSTNAME}
      - seed.hosts=["http://10.128.0.101/","http://10.128.0.102/","http://10.128.0.103/"]
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1